from turtle import*
win=Turtle()
win.showturtle()
sc=Screen()
sc.bgcolor('black')
win.speed(1)
penup()
win.forward(-220)
win.left(90)
win.forward(90)

pendown()

#win.color('black','white')
win.color('orange','red')
for i in range(2):
    win.fillcolor('orange')
    win.begin_fill()
    win.color('orange','orange')
    win.forward(149)
    win.right(90)
    win.forward(430)
    win.right(90)
    win.end_fill()
penup()
win.goto(-219,-60)
pendown()
for i in range(2):
    win.fillcolor('white')
    win.begin_fill()
    win.color('white','white')
    win.forward(149)
    win.right(90)
    win.forward(430)
    win.right(90)
    win.end_fill()
penup()
win.goto(-219,-210)
pendown()
for i in range(2):
    win.fillcolor('green')
    win.begin_fill()
    win.color('white','green')
    win.forward(149)
    win.right(90)
    win.forward(430)
    win.right(90)
    win.end_fill()
for i in range(24):
    win.penup()
    win.goto(0,15)
    win.pendown()
    win.width(2)
    win.color('navy blue','navy blue')
    win.forward(75)
    win.right(15)
    win.penup()
    win.goto(0,0)
    win.pendown()
win.penup()
win.goto(75,13)
win.pendown()
win.circle(75)

win.hideturtle()


done()